<a href="https://colab.research.google.com/github/Duchuy-05/SamSung_Inovation_Campus_2026/blob/master/Exam1015.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Làm việc với Series

In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.Series(['Male', 'female', 'male', 'male', 'female', 'female', 'female'])

0      Male
1    female
2      male
3      male
4    female
5    female
6    female
dtype: object

In [4]:
dict_data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
dict_data

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [5]:
pd.Series(dict_data)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
ser1 = pd.Series(dict_data)
ser1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
type(ser1)

pandas.core.series.Series

In [11]:
ser1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [12]:
ser1.values

array([1, 2, 3, 4, 5])

In [14]:
list_data = ['2005-05-11', 3.14, 'ABC', 100, True]
ser2 = pd.Series(list_data)
ser2

0    2005-05-11
1          3.14
2           ABC
3           100
4          True
dtype: object

In [52]:
df = pd.DataFrame({
    'Name': ['Huy', 'Alex', 'Kien'],
    'Age': ['18', '19', '20'],
    'Sex': ['Male', 'Male', 'Female']
})
df

   Name Age     Sex
0   Huy  18    Male
1  Alex  19    Male
2  Kien  20  Female

In [22]:
df['Age']

0    18
1    19
2    20
Name: Age, dtype: object

In [23]:
type(['Age'])

list

In [27]:
df['Age'][0]

'18'

In [30]:
df = pd.DataFrame(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
df.columns

RangeIndex(start=0, stop=3, step=1)

In [33]:
df[1]

0    2
1    5
2    8
Name: 1, dtype: int64

In [36]:
type(df[0])

pandas.core.series.Series

In [38]:
eye = pd.Series({  #Tạo một Series bằng cách chỉ mục
    'Brow': 1000, 'Blue': 200, 'Green': 160
})
eye

Brow     1000
Blue      200
Green     160
dtype: int64

In [39]:
eye.values

array([1000,  200,  160])

In [40]:
eye.name

In [42]:
eye.index

Index(['Brow', 'Blue', 'Green'], dtype='object')

In [43]:
eye.name = 'eye color'

In [44]:
eye.sort_values()

Green     160
Blue      200
Brow     1000
Name: eye color, dtype: int64

In [45]:
eye.sort_index()

Blue      200
Brow     1000
Green     160
Name: eye color, dtype: int64

In [46]:
eye.unique()

array([1000,  200,  160])

In [47]:
eye.nunique()

3

#### Ghép 2 mảng vào 1 Series

In [49]:
my_data2 = [220, 215, 93, 64, 64]
my_index = ['Brow', 'Blue', 'Huy', 'Tuan', 'Green']

In [50]:
eye2 = pd.Series(my_data2, index=my_index)
eye2

Brow     220
Blue     215
Huy       93
Tuan      64
Green     64
dtype: int64

In [51]:
eye2.value_counts()

64     2
220    1
215    1
93     1
Name: count, dtype: int64

#### Chỉ mục và lát cắt trong Series

In [54]:
ser = pd.Series([0,10,20,30,40,50], ['a', 'b', 'c', 'd', 'e', 'f'])
ser

a     0
b    10
c    20
d    30
e    40
f    50
dtype: int64

In [56]:
ser.iloc[2] # đi trên cột data

np.int64(20)

In [58]:
ser.loc['b'] # đi trên cột index

np.int64(10)

In [59]:
ser.iloc[1:3]

b    10
c    20
dtype: int64

#### Các phép toán trong Series

In [61]:
ser1 = pd.Series(data = [10,20,30,40,5], index=['a', 'b', 'c', 'd', 'e'])
ser2 = pd.Series(data = [10,25,35,40,50], index=['e', 'd', 'c', 'b', 'a'])

In [62]:
ser1 + ser2

a    60
b    60
c    65
d    65
e    15
dtype: int64

In [63]:
ser1.sum()

np.int64(105)

In [64]:
ser1.min()

5

In [65]:
ser1.mean() # giá trị trung bình

np.float64(21.0)

In [66]:
ser1.median() # giá trị trung vị

20.0

In [67]:
ser1.max()

40

In [68]:
ser1.std() # độ lệch chuẩn

14.317821063276353

In [69]:
ser1.var() # Phương sai

205.0

#### Sử dụng hàm lamba trong Series

In [75]:
ser_heigh = pd.Series([150, 170, 180], name='heigh')

In [76]:
plus_10 = lambda x: x + 10
plus_10(200)

210

In [79]:
ser= ser_heigh.apply(lambda x: x + 20)
ser

0    170
1    190
2    200
Name: heigh, dtype: int64

#### Tạo dataFrame từ file 'csv'

In [81]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [83]:
import pandas as pd
file_path = '/content/drive/MyDrive/Colab Notebooks/mldata/mandir-marg, delhi-air-quality.csv'
df = pd.read_csv(file_path)
display(df.head())

       date  pm25  pm10    o3  no2  so2  co
0  2026/5/1   160    95   214    2   16   2
1  2026/5/2   168   118          2   12   4
2  2026/5/3   171    71    13    1   10   3
3  2026/5/4   151    76    93    2    9   5
4  2026/5/5   162   110    26    2   14   8

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4413 entries, 0 to 4412
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    4413 non-null   object
 1    pm25   4413 non-null   object
 2    pm10   4413 non-null   object
 3    o3     4413 non-null   object
 4    no2    4413 non-null   object
 5    so2    4413 non-null   object
 6    co     4413 non-null   object
dtypes: object(7)
memory usage: 241.5+ KB

In [87]:
df.tail()

            date  pm25  pm10   o3  no2  so2   co
4408  2013/12/31         196   30   11    9   19
4409   2014/1/19         127   14   16    7   24
4410   2014/1/26         144   26   32    8   19
4411   2014/2/16         109   18   25    7   16
4412   2014/8/24               23   27    5    3

In [89]:
df.columns

Index(['date', ' pm25', ' pm10', ' o3', ' no2', ' so2', ' co'], dtype='object')

In [91]:
df.index

RangeIndex(start=0, stop=4413, step=1)

In [97]:
df[' pm10']

0         95
1        118
2         71
3         76
4        110
        ...
4408     196
4409     127
4410     144
4411     109
4412
Name:  pm10, Length: 4413, dtype: object