<a href="https://colab.research.google.com/github/Duchuy-05/SamSung_Inovation_Campus_2026/blob/master/Practice27_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Transforming DataFrames:

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df = pd.read_csv('/content/drive/My Drive/Slides/Examples/Chapter 3/data_studentlist.csv', header='infer')

In [ ]:
df.colums = ['NAME', 'GENDER', 'GRADE', 'ABSENCES', 'BLOODTYPE', 'HEIGHT', 'WEIGHT']
df.head()

              name gender  age  grade absence bloodtype  height  weight
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriquez      F   20      1       Y         A   168.0    49.5

### 1.1 Merging DataFrames

In [ ]:
df_left = df.loc[:, ['name', 'age', 'gender', 'grade', 'absence']]
df_left_small = df_left.loc[:10, ]
df_left_small

                name  age gender  grade absence
0      Jared Diamond   23      M      3       Y
1     Sarah O'Donnel   22      F      2       N
2       Brian Martin   24      M      4       N
3       David Hassel   23      M      3       N
4    Clara Rodriquez   20      F      1       Y
5   Jennifer Lorentz   21      F      2       N
6        Susan Clark   22      F      1       N
7    Margareth Jones   23      F      1       N
8       John Bertsch   23      M      3       N
9     Jake Timmerman   22      M      2       N
10     Joshua Connor   24      M      4       Y

In [ ]:
df_right = df.loc[:, ['name', 'bloodtype', 'height', 'weight']]
df_right_small = df_right.loc[7:, ]
df_right_small

                name bloodtype  height  weight
7    Margareth Jones         A   176.9    55.0
8       John Bertsch         B   178.5    64.2
9     Jake Timmerman         B   176.1    61.3
10     Joshua Connor         O   167.1    62.0
11      John Matsuda        AB   180.0    75.8
12      Eddy Johnson         A   162.2    55.3
13  Rebecah Anderson         O   176.1    53.1
14      Linda Carter         B   158.2    45.2
15    Richard Swayze         B   168.6    70.2
16       Andrew King         A   169.2    62.2

Inner join

In [ ]:
pd.merge(df_left_small, df_right_small, on='name', how='inner')

              name  age gender  grade absence bloodtype  height  weight
0  Margareth Jones   23      F      1       N         A   176.9    55.0
1     John Bertsch   23      M      3       N         B   178.5    64.2
2   Jake Timmerman   22      M      2       N         B   176.1    61.3
3    Joshua Connor   24      M      4       Y         O   167.1    62.0

Left join

In [ ]:
pd.merge(df_left_small, df_right_small,left_on='name', right_on='name', how='left')

                name  age gender  grade absence bloodtype  height  weight
0      Jared Diamond   23      M      3       Y       NaN     NaN     NaN
1     Sarah O'Donnel   22      F      2       N       NaN     NaN     NaN
2       Brian Martin   24      M      4       N       NaN     NaN     NaN
3       David Hassel   23      M      3       N       NaN     NaN     NaN
4    Clara Rodriquez   20      F      1       Y       NaN     NaN     NaN
5   Jennifer Lorentz   21      F      2       N       NaN     NaN     NaN
6        Susan Clark   22      F      1       N       NaN     NaN     NaN
7    Margareth Jones   23      F      1       N         A   176.9    55.0
8       John Bertsch   23      M      3       N         B   178.5    64.2
9     Jake Timmerman   22      M      2       N         B   176.1    61.3
10     Joshua Connor   24      M      4       Y         O   167.1    62.0

Right Join

In [ ]:
pd.merge(df_left_small, df_right_small, left_on='name', right_on='name', how='right')

               name   age gender  grade absence bloodtype  height  weight
0   Margareth Jones  23.0      F    1.0       N         A   176.9    55.0
1      John Bertsch  23.0      M    3.0       N         B   178.5    64.2
2    Jake Timmerman  22.0      M    2.0       N         B   176.1    61.3
3     Joshua Connor  24.0      M    4.0       Y         O   167.1    62.0
4      John Matsuda   NaN    NaN    NaN     NaN        AB   180.0    75.8
5      Eddy Johnson   NaN    NaN    NaN     NaN         A   162.2    55.3
6  Rebecah Anderson   NaN    NaN    NaN     NaN         O   176.1    53.1
7      Linda Carter   NaN    NaN    NaN     NaN         B   158.2    45.2
8    Richard Swayze   NaN    NaN    NaN     NaN         B   168.6    70.2
9       Andrew King   NaN    NaN    NaN     NaN         A   169.2    62.2

Full outer join:

In [ ]:
pd.merge(df_left_small, df_right_small,left_on='name', right_on='name', how='outer')

                name   age gender  grade absence bloodtype  height  weight
0        Andrew King   NaN    NaN    NaN     NaN         A   169.2    62.2
1       Brian Martin  24.0      M    4.0       N       NaN     NaN     NaN
2    Clara Rodriquez  20.0      F    1.0       Y       NaN     NaN     NaN
3       David Hassel  23.0      M    3.0       N       NaN     NaN     NaN
4       Eddy Johnson   NaN    NaN    NaN     NaN         A   162.2    55.3
5     Jake Timmerman  22.0      M    2.0       N         B   176.1    61.3
6      Jared Diamond  23.0      M    3.0       Y       NaN     NaN     NaN
7   Jennifer Lorentz  21.0      F    2.0       N       NaN     NaN     NaN
8       John Bertsch  23.0      M    3.0       N         B   178.5    64.2
9       John Matsuda   NaN    NaN    NaN     NaN        AB   180.0    75.8
10     Joshua Connor  24.0      M    4.0       Y         O   167.1    62.0
11      Linda Carter   NaN    NaN    NaN     NaN         B   158.2    45.2
12   Margareth Jones  23.0      F    1.0       N         A   176.9    55.0
13  Rebecah Anderson   NaN    NaN    NaN     NaN         O   176.1    53.1
14    Richard Swayze   NaN    NaN    NaN     NaN         B   168.6    70.2
15    Sarah O'Donnel  22.0      F    2.0       N       NaN     NaN     NaN
16       Susan Clark  22.0      F    1.0       N       NaN     NaN     NaN

### 1.2 Binding DataFrames

Bind vertically matched by 'column':

In [ ]:
pd.concat([df_left_small, df_right_small], sort= True)

   absence   age bloodtype gender  grade  height              name  weight
0        Y  23.0       NaN      M    3.0     NaN     Jared Diamond     NaN
1        N  22.0       NaN      F    2.0     NaN    Sarah O'Donnel     NaN
2        N  24.0       NaN      M    4.0     NaN      Brian Martin     NaN
3        N  23.0       NaN      M    3.0     NaN      David Hassel     NaN
4        Y  20.0       NaN      F    1.0     NaN   Clara Rodriquez     NaN
5        N  21.0       NaN      F    2.0     NaN  Jennifer Lorentz     NaN
6        N  22.0       NaN      F    1.0     NaN       Susan Clark     NaN
7        N  23.0       NaN      F    1.0     NaN   Margareth Jones     NaN
8        N  23.0       NaN      M    3.0     NaN      John Bertsch     NaN
9        N  22.0       NaN      M    2.0     NaN    Jake Timmerman     NaN
10       Y  24.0       NaN      M    4.0     NaN     Joshua Connor     NaN
7      NaN   NaN         A    NaN    NaN   176.9   Margareth Jones    55.0
8      NaN   NaN         B    NaN    NaN   178.5      John Bertsch    64.2
9      NaN   NaN         B    NaN    NaN   176.1    Jake Timmerman    61.3
10     NaN   NaN         O    NaN    NaN   167.1     Joshua Connor    62.0
11     NaN   NaN        AB    NaN    NaN   180.0      John Matsuda    75.8
12     NaN   NaN         A    NaN    NaN   162.2      Eddy Johnson    55.3
13     NaN   NaN         O    NaN    NaN   176.1  Rebecah Anderson    53.1
14     NaN   NaN         B    NaN    NaN   158.2      Linda Carter    45.2
15     NaN   NaN         B    NaN    NaN   168.6    Richard Swayze    70.2
16     NaN   NaN         A    NaN    NaN   169.2       Andrew King    62.2

Bind horizontally matched by 'index'

In [ ]:
pd.concat([df_left_small, df_right_small], axis=1, sort= True)

,name,age,gender,grade,absence,name,bloodtype,height,weight
0,Jared Diamond,23.0,M,3.0,Y,NaN,NaN,NaN,NaN
1,Sarah O'Donnel,22.0,F,2.0,N,NaN,NaN,NaN,NaN
2,Brian Martin,24.0,M,4.0,N,NaN,NaN,NaN,NaN
3,David Hassel,23.0,M,3.0,N,NaN,NaN,NaN,NaN
4,Clara Rodriquez,20.0,F,1.0,Y,NaN,NaN,NaN,NaN
5,Jennifer Lorentz,21.0,F,2.0,N,NaN,NaN,NaN,NaN
6,Susan Clark,22.0,F,1.0,N,NaN,NaN,NaN,NaN
7,Margareth Jones,23.0,F,1.0,N,Margareth Jones,A,176.9,55.0
8,John Bertsch,23.0,M,3.0,N,John Bertsch,B,178.5,64.2
9,Jake Timmerman,22.0,M,2.0,N,Jake Timmerman,B,176.1,61.3
10,Joshua Connor,24.0,M,4.0,Y,Joshua Connor,O,167.1,62.0
11,NaN,NaN,NaN,NaN,NaN,John Matsuda,AB,180.0,75.8
12,NaN,NaN,NaN,NaN,NaN,Eddy Johnson,A,162.2,55.3
13,NaN,NaN,NaN,NaN,NaN,Rebecah Anderson,O,176.1,53.1
14,NaN,NaN,NaN,NaN,NaN,Linda Carter,B,158.2,45.2
15,NaN,NaN,NaN,NaN,NaN,Richard Swayze,B,168.6,70.2
16,NaN,NaN,NaN,NaN,NaN,Andrew King,A,169.2,62.2

### 2. Data Fearture Engineering:

#### 2.1 Add Columns:

In [ ]:
df = pd.read_csv('/content/drive/My Drive/Slides/Examples/Chapter 3/TV_Sales.csv', header='infer')
df.head()

   sales  comp_price  income  price shelve_loc city local
0   9.50        1932      73   1680        Bad  Yes   Yes
1  11.22        1554      48   1162       Good  Yes   Yes
2  10.06        1582      35   1120     Medium  Yes   Yes
3   7.40        1638     100   1358     Medium  Yes   Yes
4   4.15        1974      64   1792        Bad  Yes    No

In [ ]:
df['price_diff'] = df['price'] - df['comp_price']
df.head()

   sales  comp_price  income  price shelve_loc city local  price_diff
0   9.50        1932      73   1680        Bad  Yes   Yes        -252
1  11.22        1554      48   1162       Good  Yes   Yes        -392
2  10.06        1582      35   1120     Medium  Yes   Yes        -462
3   7.40        1638     100   1358     Medium  Yes   Yes        -280
4   4.15        1974      64   1792        Bad  Yes    No        -182

In [ ]:
df['price_tot'] = df['price'] * df['sales']
df.head( )

,sales,comp_price,income,price,shelve_loc,city,local,price_diff,price_tot
0,9.50,1932,73,1680,Bad,Yes,Yes,-252,15960.00
1,11.22,1554,48,1162,Good,Yes,Yes,-392,13037.64
2,10.06,1582,35,1120,Medium,Yes,Yes,-462,11267.20
3,7.40,1638,100,1358,Medium,Yes,Yes,-280,10049.20
4,4.15,1974,64,1792,Bad,Yes,No,-182,7436.80

#### 2.2 Data Type Conversion

In [ ]:
df.dtypes

sales         float64
comp_price      int64
income          int64
price           int64
shelve_loc     object
city           object
local          object
price_diff      int64
price_tot     float64
dtype: object

In [ ]:
df['price_tot'] = df['price_tot'].astype(int)
df.dtypes

sales         float64
comp_price      int64
income          int64
price           int64
shelve_loc     object
city           object
local          object
price_diff      int64
price_tot       int64
dtype: object

#### 2.3. Categorical Data Conversion:

In [ ]:
count, bin_dividers = np.histogram(df['price'], bins=3)
print(count)
print(bin_dividers)

[ 24 306  70]
[ 336.         1115.33333333 1894.66666667 2674.        ]

In [ ]:
bin_names = ['Low Sales', 'Normal Sales', 'High Sales']

df['sales_bin'] = pd.cut(x=df['sales'],
                     bins=bin_dividers,
                     labels=bin_names,
                     include_lowest=True)

df.head()

,sales,comp_price,income,price,shelve_loc,city,local,price_diff,price_tot,sales_bin
0,9.50,1932,73,1680,Bad,Yes,Yes,-252,15960,NaN
1,11.22,1554,48,1162,Good,Yes,Yes,-392,13037,NaN
2,10.06,1582,35,1120,Medium,Yes,Yes,-462,11267,NaN
3,7.40,1638,100,1358,Medium,Yes,Yes,-280,10049,NaN
4,4.15,1974,64,1792,Bad,Yes,No,-182,7436,NaN

#### 2.4 One-Hot Vector:

In [ ]:
sales_dummies = pd.get_dummies(df['sales_bin']).astype('int')
sales_dummies.head()

   Low Sales  Normal Sales  High Sales
0          0             0           0
1          0             0           0
2          0             0           0
3          0             0           0
4          0             0           0

#### 2.5 Normalization

In [ ]:
df['sales'].describe()  #std: độ lệnh chuẩn, mean: trung bình cộng

count    400.000000
mean       7.496325
std        2.824115
min        0.000000
25%        5.390000
50%        7.490000
75%        9.320000
max       16.270000
Name: sales, dtype: float64

In [ ]:
df['sales'] = (df['sales'] - df['sales'].min()) / (df['sales'].max() - df['sales'].min())
df['sales'].describe()

count    400.000000
mean       0.460745
std        0.173578
min        0.000000
25%        0.331285
50%        0.460356
75%        0.572833
max        1.000000
Name: sales, dtype: float64

In [ ]:
cols = ['comp_price', 'income', 'price', 'price_diff', 'price_tot']
df[cols].describe()

        comp_price      income        price  price_diff     price_tot
count   400.000000  400.000000   400.000000  400.000000    400.000000
mean   1749.650000   68.657500  1621.130000 -128.520000  11736.572500
std     214.683161   27.986037   331.473301  269.677296   4236.234235
min    1078.000000   21.000000   336.000000 -798.000000      0.000000
25%    1610.000000   42.750000  1400.000000 -297.500000   8771.500000
50%    1750.000000   69.000000  1638.000000 -126.000000  11539.500000
75%    1890.000000   91.000000  1834.000000   56.000000  14295.500000
max    2450.000000  120.000000  2674.000000  644.000000  25119.000000

After running the above cell, you will be prompted to authorize Colab to access your Google Drive. Follow the instructions to complete the mounting process. Once mounted, your Drive contents will be accessible under `/content/drive`.